
#Personalization
spring.application.name=PuppetMaster
spring.main.banner-mode=off
logging.level.root=warn

#Java Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/puppetmaster
spring.datasource.username=PuppetMasterEditor
spring.datasource.password=Ic@nd0allth1ngs
spring.jpa.open-in-view=true

#Custom properties
team.name =Followers of God Puppet Team

#Security
management.endpoints.web.exposure.include=*
management.info.env.enabled=true